# Generated by Django 4.0.1 on 2022-02-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='Stories/images'),
        ),
    ]
